import type { Config } from "tailwindcss";

/**
 * Tailwind theme for the Freelancey app.
 *
 * The semantic tokens below are ported 1:1 from the NextAdmin template
 * (`dashboard/src/app/globals.css` + `dashboard/src/app/css/default.css`) so
 * components can be shared between the design reference and this application
 * using identical class names. Every value resolves to a CSS variable declared
 * in `src/app/globals.css` — never hardcode a hex value in a component.
 */
const config: Config = {
  // The `dark` class on <html> switches the token values in globals.css.
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        /* ---- Brand / primary ---- */
        primary: {
          50: "var(--primary-50)",
          100: "var(--primary-100)",
          200: "var(--primary-200)",
          300: "var(--primary-300)",
          400: "var(--primary-400)",
          500: "var(--primary-500)",
          600: "var(--primary-600)",
          700: "var(--primary-700)",
          800: "var(--primary-800)",
          900: "var(--primary-900)",
          950: "var(--primary-950)",
          text: "var(--primary-text)",
        },
        brand: {
          100: "var(--brand-100)",
          200: "var(--brand-200)",
          300: "var(--brand-300)",
          400: "var(--brand-400)",
          500: "var(--brand-500)",
          600: "var(--brand-600)",
        },
        "neutral-brand-color": "var(--neutral-brand-color)",

        /* ---- Text ---- */
        text: {
          50: "var(--text-50)",
          100: "var(--text-100)",
          200: "var(--text-200)",
          300: "var(--text-300)",
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          tertiary: "var(--text-tertiary)",
          disable: "var(--text-disable)",
        },
        title: {
          50: "var(--title-50)",
        },

        /* ---- Context ---- */
        "error-500": "var(--error-500)",
        "success-500": "var(--success-500)",
        "warning-500": "var(--warning-500)",
        "info-500": "var(--info-500)",

        /* ---- Whites ---- */
        "white-100": "var(--white-100)",
        "white-90": "var(--white-90)",
        "white-80": "var(--white-80)",
        "white-70": "var(--white-70)",
        "white-60": "var(--white-60)",
        "base-white": "var(--base-white)",

        /* ---- Borders ---- */
        "border-color-base-50": "var(--border-color-base-50)",
        "border-color-base-100": "var(--border-color-base-100)",
        "border-color-base-200": "var(--border-color-base-200)",
        "border-color-base-300": "var(--border-color-base-300)",
        "border-primary": "var(--border-primary)",
        "border-secondary": "var(--border-secondary)",
        "border-secondary-alt": "var(--border-secondary-alt)",
        "card-border": "var(--card-border)",
        "card-surface-border": "var(--card-surface-border)",
        "input-border": "var(--input-border)",

        /* ---- Foreground ---- */
        foreground: {
          50: "var(--foreground-50)",
          100: "var(--foreground-100)",
          soft: {
            50: "var(--foreground-soft-50)",
            100: "var(--foreground-soft-100)",
            200: "var(--foreground-soft-200)",
            300: "var(--foreground-soft-300)",
            400: "var(--foreground-soft-400)",
            500: "var(--foreground-soft-500)",
          },
        },

        /* ---- Backgrounds ---- */
        background: {
          50: "var(--background-50)",
          100: "var(--background-100)",
          soft: {
            50: "var(--background-soft-50)",
            100: "var(--background-soft-100)",
            200: "var(--background-soft-200)",
            300: "var(--background-soft-300)",
            400: "var(--background-soft-400)",
            500: "var(--background-soft-500)",
          },
          success: { 600: "var(--background-success-600)" },
          gray: {
            primary: "var(--background-gray-primary)",
            secondary: "var(--background-gray-secondary)",
            secondary_alt: "var(--background-gray-secondary_alt)",
            secondary_alt_2: "var(--background-gray-secondary_alt_2)",
            tertiary: "var(--background-gray-tertiary)",
            quaternary: "var(--background-gray-quaternary)",
          },
          white: {
            primary: "var(--background-white-primary)",
            secondary: "var(--background-white-secondary)",
          },
        },

        /* ---- Icons ---- */
        icon: {
          primary: "var(--icon-primary)",
          secondary: "var(--icon-secondary)",
          tertiary: "var(--icon-tertiary)",
        },

        /* ---- Cards ---- */
        card: {
          background: "var(--card-background)",
          50: "var(--card-background-50)",
          100: "var(--card-background-100)",
          200: "var(--card-background-200)",
          300: "var(--card-background-300)",
          "surface-area": "var(--card-surface-area)",
        },

        /* ---- Buttons ---- */
        "button-primary-background": "var(--button-primary-background)",
        "button-primary-hover-background": "var(--button-primary-hover-background)",
        "button-primary-text": "var(--button-primary-text)",
        "button-primary-focus-ring": "var(--button-primary-focus-ring)",
        "button-primary-outline-background": "var(--button-primary-outline-background)",
        "button-primary-outline-hover-background": "var(--button-primary-outline-hover-background)",
        "button-primary-outline-text": "var(--button-primary-outline-text)",
        "button-primary-outline-stroke": "var(--button-primary-outline-stroke)",
        "button-outline-background": "var(--button-outline-background)",
        "button-outline-hover-background": "var(--button-outline-hover-background)",
        "button-outline-border": "var(--button-outline-border)",
        "button-outline-focus-ring": "var(--button-outline-focus-ring)",
        "button-outline-text": "var(--button-outline-text)",
        "button-outline-hover-text": "var(--button-outline-hover-text)",
        "button-outline-disabled-background": "var(--button-outline-disabled-background)",
        "button-outline-disabled-text": "var(--button-outline-disabled-text)",
        "button-outline-disabled-border": "var(--button-outline-disabled-border)",
        "button-disabled-background": "var(--button-disabled-background)",
        "button-disabled-border": "var(--button-disabled-border)",
        "button-disabled-text": "var(--button-disabled-text)",
        "button-error-background": "var(--button-error-background)",
        "button-error-hover-background": "var(--button-error-hover-background)",
        "button-error-border": "var(--button-error-border)",
        "button-error-text": "var(--button-error-text)",
        "button-error-focus-ring": "var(--button-error-focus-ring)",
        "button-error-outline-background": "var(--button-error-outline-background)",
        "button-error-outline-hover-background": "var(--button-error-outline-hover-background)",
        "button-error-outline-border": "var(--button-error-outline-border)",
        "button-error-outline-text": "var(--button-error-outline-text)",
        "button-error-outline-hover-text": "var(--button-error-outline-hover-text)",
        "button-error-outline-focus-ring": "var(--button-error-outline-focus-ring)",
        "button-error-outline-stroke": "var(--button-error-outline-stroke)",
        "button-success-background": "var(--button-success-background)",
        "button-success-hover-background": "var(--button-success-hover-background)",
        "button-success-border": "var(--button-success-border)",
        "button-success-text": "var(--button-success-text)",
        "button-success-focus-ring": "var(--button-success-focus-ring)",
        "button-success-outline-background": "var(--button-success-outline-background)",
        "button-success-outline-hover-background": "var(--button-success-outline-hover-background)",
        "button-success-outline-border": "var(--button-success-outline-border)",
        "button-success-outline-text": "var(--button-success-outline-text)",
        "button-success-outline-hover-text": "var(--button-success-outline-hover-text)",
        "button-success-outline-focus-ring": "var(--button-success-outline-focus-ring)",
        "button-ghost-text": "var(--button-ghost-text)",
        "button-ghost-hover-text": "var(--button-ghost-hover-text)",
        "button-ghost-hover-background": "var(--button-ghost-hover-background)",
        "button-group-primary-background": "var(--button-group-primary-background)",
        "button-group-primary-hover-background": "var(--button-group-primary-hover-background)",
        "button-group-primary-text": "var(--button-group-primary-text)",
        "button-group-secondary-background": "var(--button-group-secondary-background)",
        "button-group-secondary-text": "var(--button-group-secondary-text)",

        /* ---- Badges ---- */
        "badge-neutral-background": "var(--badge-neutral-background)",
        "badge-neutral-text": "var(--badge-neutral-text)",
        "badge-neutral-icon-color": "var(--badge-neutral-icon-color)",
        "badge-primary-background": "var(--badge-primary-background)",
        "badge-primary-text": "var(--badge-primary-text)",
        "badge-primary-icon-color": "var(--badge-primary-icon-color)",
        "badge-error-background": "var(--badge-error-background)",
        "badge-error-text": "var(--badge-error-text)",
        "badge-error-icon-color": "var(--badge-error-icon-color)",
        "badge-warning-background": "var(--badge-warning-background)",
        "badge-warning-text": "var(--badge-warning-text)",
        "badge-warning-icon-color": "var(--badge-warning-icon-color)",
        "badge-success-background": "var(--badge-success-background)",
        "badge-success-text": "var(--badge-success-text)",
        "badge-success-icon-color": "var(--badge-success-icon-color)",
        "badge-cyan-background": "var(--badge-cyan-background)",
        "badge-cyan-text": "var(--badge-cyan-text)",
        "badge-cyan-icon-color": "var(--badge-cyan-icon-color)",
        "badge-sky-background": "var(--badge-sky-background)",
        "badge-sky-text": "var(--badge-sky-text)",
        "badge-sky-icon-color": "var(--badge-sky-icon-color)",
        "badge-blue-background": "var(--badge-blue-background)",
        "badge-blue-text": "var(--badge-blue-text)",
        "badge-blue-icon-color": "var(--badge-blue-icon-color)",
        "badge-violet-background": "var(--badge-violet-background)",
        "badge-violet-text": "var(--badge-violet-text)",
        "badge-violet-icon-color": "var(--badge-violet-icon-color)",
        "badge-purple-background": "var(--badge-purple-background)",
        "badge-purple-text": "var(--badge-purple-text)",
        "badge-purple-icon-color": "var(--badge-purple-icon-color)",
        "badge-pink-background": "var(--badge-pink-background)",
        "badge-pink-text": "var(--badge-pink-text)",
        "badge-pink-icon-color": "var(--badge-pink-icon-color)",
        "badge-rose-background": "var(--badge-rose-background)",
        "badge-rose-text": "var(--badge-rose-text)",
        "badge-rose-icon-color": "var(--badge-rose-icon-color)",
        "badge-orange-background": "var(--badge-orange-background)",
        "badge-orange-text": "var(--badge-orange-text)",
        "badge-orange-icon-color": "var(--badge-orange-icon-color)",
        "badge-gray-background": "var(--badge-gray-background)",
        "badge-gray-icon": "var(--badge-gray-icon)",

        /* ---- Sidebar ---- */
        "sidebar-nav-default-background": "var(--sidebar-nav-default-background)",
        "sidebar-nav-hover-background": "var(--sidebar-nav-hover-background)",
        "sidebar-nav-secondary-hover-background": "var(--sidebar-nav-secondary-hover-background)",
        "sidebar-nav-hover-text": "var(--sidebar-nav-hover-text)",
        "sidebar-nav-active-text": "var(--sidebar-nav-active-text)",
        "sidebar-nav-active-background": "var(--sidebar-nav-active-background)",
        "sidebar-nav-focused-background": "var(--sidebar-nav-focused-background)",
        "sidebar-nav-default-text": "var(--sidebar-nav-default-text)",
        "sidebar-nav-icon": "var(--sidebar-nav-icon)",
        "sidebar-nav-item-hover-background": "var(--sidebar-navigation-nav-item-nav-hover-background)",
        "sidebar-badge-background": "var(--sidebar-badge-background)",
        "sidebar-badge-text": "var(--sidebar-badge-text)",
        "sidebar-footer-background": "var(--sidebar-footer-background)",
        "sidebar-footer-title": "var(--sidebar-footer-title)",
        "sidebar-footer-subtitle": "var(--sidebar-footer-subtitle)",
        "sidebar-footer-button-text": "var(--sidebar-footer-button-text)",
        "sidebar-background": "var(--sidebar-background)",
        "sidebar-border": "var(--sidebar-border)",

        /* ---- Inputs ---- */
        "input-background": "var(--input-background)",
        "input-label-text": "var(--input-label-text)",
        "input-label-text-color": "var(--input-label-text-color)",
        "input-disabled-text": "var(--input-disabled-text)",
        "input-disabled-background": "var(--input-disabled-background)",
        "input-disabled-border": "var(--input-disabled-border)",
        "input-placeholder-text": "var(--input-placeholder-text)",
        "input-placeholder-text-color": "var(--input-placeholder-text-color)",
        "input-primary-focus-border": "var(--input-primary-focus-border)",
        "input-error-focus-border": "var(--input-error-focus-border)",
        "input-success-focus-border": "var(--input-success-focus-border)",
        "input-error": "var(--input-error)",
        "input-success": "var(--input-success)",

        /* ---- Alerts ---- */
        "alert-success-background": "var(--alert-success-background)",
        "alert-success-border": "var(--alert-success-border)",
        "alert-success-title": "var(--alert-success-title)",
        "alert-success-description": "var(--alert-success-description)",
        "alert-success-icon-background": "var(--alert-success-icon-background)",
        "alert-success-button-background": "var(--alert-success-button-background)",
        "alert-success-button-hover-background": "var(--alert-success-button-hover-background)",
        "alert-success-button-text": "var(--alert-success-button-text)",
        "alert-danger-background": "var(--alert-danger-background)",
        "alert-danger-border": "var(--alert-danger-border)",
        "alert-danger-title": "var(--alert-danger-title)",
        "alert-danger-description": "var(--alert-danger-description)",
        "alert-danger-icon-background": "var(--alert-danger-icon-background)",
        "alert-danger-button-background": "var(--alert-danger-button-background)",
        "alert-danger-button-hover-background": "var(--alert-danger-button-hover-background)",
        "alert-danger-button-text": "var(--alert-danger-button-text)",
        "alert-warning-background": "var(--alert-warning-background)",
        "alert-warning-border": "var(--alert-warning-border)",
        "alert-warning-title": "var(--alert-warning-title)",
        "alert-warning-description": "var(--alert-warning-description)",
        "alert-warning-icon-background": "var(--alert-warning-icon-background)",
        "alert-warning-button-background": "var(--alert-warning-button-background)",
        "alert-warning-button-hover-background": "var(--alert-warning-button-hover-background)",
        "alert-warning-button-text": "var(--alert-warning-button-text)",
        "alert-info-background": "var(--alert-info-background)",
        "alert-info-border": "var(--alert-info-border)",
        "alert-info-title": "var(--alert-info-title)",
        "alert-info-description": "var(--alert-info-description)",
        "alert-info-icon-background": "var(--alert-info-icon-background)",
        "alert-info-button-background": "var(--alert-info-button-background)",
        "alert-info-button-hover-background": "var(--alert-info-button-hover-background)",
        "alert-info-button-text": "var(--alert-info-button-text)",
        "alert-default-background": "var(--alert-default-background)",
        "alert-default-border": "var(--alert-default-border)",
        "alert-default-title": "var(--alert-default-title)",
        "alert-default-description": "var(--alert-default-description)",
        "alert-default-icon-background": "var(--alert-default-icon-background)",
        "alert-default-button-background": "var(--alert-default-button-background)",
        "alert-default-button-hover-background": "var(--alert-default-button-hover-background)",
        "alert-default-button-text": "var(--alert-default-button-text)",

        /* ---- Tabs / checkbox / toggle ---- */
        "tab-background": "var(--tab-background)",
        "tab-active-background": "var(--tab-active-background)",
        "tab-secondary-active-background": "var(--tab-secondary-active-background)",
        "checkbox-background": "var(--checkbox-background)",
        "checkbox-checked-border": "var(--checkbox-checked-border)",
        "checkbox-checked-background": "var(--checkbox-checked-background)",
        "checkbox-checked-icon-color": "var(--checkbox-checked-icon-color)",
        "toggle-default-background": "var(--toggle-default-background)",
        "toggle-disabled-foreground": "var(--toggle-disabled-foreground)",
        "toggle-disabled-background": "var(--toggle-disabled-background)",
        "toggle-active-background": "var(--toggle-active-background)",

        /* ---- Overlays ---- */
        "dropdown-background": "var(--dropdown-background)",
        "dropdown-hover-background": "var(--dropdown-hover-background)",
        "dropdown-secondary-background": "var(--dropdown-secondary-background)",
        "dropdown-divider": "var(--dropdown-divider)",
        "dropdowns-background": "var(--dropdowns-background)",
        "tooltip-text": "var(--tooltip-text)",
        "tooltip-text-color": "var(--tooltip-text-color)",
        "tooltip-border": "var(--tooltip-border)",
        "tooltip-background": "var(--tooltip-background)",
        "popover-title-background": "var(--popover-title-background)",
        "popover-border": "var(--popover-border)",
        "scrollbar-background": "var(--scrollbar-background)",
        "datepicker-background": "var(--datepicker-background)",
        "datepicker-selected-background": "var(--datepicker-selected-background)",
        "datepicker-selected-hover-background": "var(--datepicker-selected-hover-background)",

        /* ---- Calendar ---- */
        "calendar-primary-badge": "var(--calendar-primary-badge)",
        "calendar-primary-background": "var(--calendar-primary-background)",
        "calendar-success-badge": "var(--calendar-success-badge)",
        "calendar-success-background": "var(--calendar-success-background)",
        "calendar-warning-badge": "var(--calendar-warning-badge)",
        "calendar-warning-background": "var(--calendar-warning-background)",
        "calendar-danger-badge": "var(--calendar-danger-badge)",
        "calendar-danger-background": "var(--calendar-danger-background)",
        "calendar-info-badge": "var(--calendar-info-badge)",
        "calendar-info-background": "var(--calendar-info-background)",
        "calendar-text": "var(--calendar-text)",
        "calendar-menu-text": "var(--calendar-menu-text)",
        "calendar-dropdown-background": "var(--calendar-dropdown-background)",

        /* ---- Section titles / mobile nav / map ---- */
        "section-title-badge": "var(--section-title-badge)",
        "section-title-badge-background": "var(--section-title-badge-background)",
        "mobile-nav-icon": "var(--mobile-nav-icon)",
        "mobile-nav-background": "var(--mobile-nav-background)",
        "mobile-nav-hover-background": "var(--mobile-nav-hover-background)",
        "map-fill": "var(--map-fill)",

        /* ---- Skeleton / modal ---- */
        "skeleton-gradient-50": "var(--skeleton-gradient-50)",
        "skeleton-gradient-100": "var(--skeleton-gradient-100)",
        "skeleton-gradient-200": "var(--skeleton-gradient-200)",
        "modal-button-success-background": "var(--modal-button-success-background)",
        "modal-button-info-background": "var(--modal-button-info-background)",
        "modal-button-warning-background": "var(--modal-button-warning-background)",
        "modal-button-error-background": "var(--modal-button-error-background)",

        /* ---- Charts ---- */
        "chart-line": "var(--chart-line)",
        "chart-grid": "var(--chart-grid)",
        "chart-tick": "var(--chart-tick)",
        "chart-legend": "var(--chart-legend)",

        /* ---- Misc template greys ---- */
        "gray-100": "var(--gray-100)",
        "green-600": "var(--green-600)",
        "red-600": "var(--red-600)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        "2xl": "var(--shadow-2xl)",
        "3xl": "var(--shadow-3xl)",
        popover: "var(--popover-shadow)",
        panel: "0 3px 6px -2px rgba(0, 0, 0, 0.02), 0 1px 1px 0 rgba(0, 0, 0, 0.04)",
      },
      spacing: {
        "4.5": "1.125rem",
        "7.5": "1.875rem",
        "8.5": "2.125rem",
        "9.5": "2.375rem",
        "10.5": "2.625rem",
        "11.5": "2.875rem",
        "12.5": "3.125rem",
        "13": "3.25rem",
        "15": "3.75rem",
        "18": "4.5rem",
        "67.5": "16.875rem",
        "70": "17.5rem",
      },
      maxWidth: {
        "140": "35rem",
        "384": "96rem",
      },
      fontFamily: {
        sans: [
          "var(--font-manrope)",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        // Numeric values only (money, metrics, durations, table number
        // columns) — pair with `tabular-nums` so digits stay fixed-width.
        numeric: [
          "var(--font-inter)",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
      },
      keyframes: {
        "toast-in": {
          from: { transform: "translateY(12px) scale(0.96)", opacity: "0" },
          to: { transform: "translateY(0) scale(1)", opacity: "1" },
        },
      },
      animation: {
        "toast-in": "toast-in 0.3s ease-out",
      },
    },
  },
  plugins: [],
};

export default config;
