import type { CSSProperties } from "react";

// Markup mirrors the original page section verbatim (mechanically
// converted from example.html: class names, structure, and inline styles
// are preserved so styles/combined.css continues to apply unmodified).
export function FeatureStickyNav() {
  return (
    <div data-keydesign-sticky={""} data-keydesign-sticky-until={"section3"} data-keydesign-sticky-scroll-offset={"80"} className={"keydesign-sticky elementor-element elementor-element-f4d4991 e-con-full elementor-hidden-tablet elementor-hidden-mobile e-flex e-con e-parent e-lazyloaded"} data-keydesign-sticky-disable-tablet={"yes"} data-keydesign-sticky-disable-mobile={"yes"} data-id={"f4d4991"} data-element_type={"container"} data-e-type={"container"} data-settings={"{\"background_background\":\"classic\"}"} style={{ "--keydesign-sticky-offset": "81px" } as CSSProperties}><div className={"elementor-element elementor-element-cc9df3f e-flex e-con-boxed e-con e-child"} data-id={"cc9df3f"} data-element_type={"container"} data-e-type={"container"}><div className={"e-con-inner"}><div className={"elementor-element elementor-element-20cece5 elementor-widget elementor-widget-keydesign-advanced-list"} data-id={"20cece5"} data-element_type={"widget"} data-e-type={"widget"} data-widget_type={"keydesign-advanced-list.default"}><div className={"kd-widget-container"}><ul className={"kd-advanced-list kd-list-layout--inline kd-badge-pos--after"} role={"list"}><li className={"kd-list-item elementor-repeater-item-9480ed5"} role={"listitem"}><a href={"#section1"} className={"kd-list-link"}><div className={"kd-list-inner"}><span className={"kd-list-icon"} aria-hidden={"true"}><i aria-hidden={"true"} className={"keydesign-icon at-store"} /></span><span className={"kd-list-content"}><h6 className={"kd-list-title"}>Invoicing</h6></span></div></a></li><li className={"kd-list-item elementor-repeater-item-3fcc1aa"} role={"listitem"}><a href={"#section2"} className={"kd-list-link"}><div className={"kd-list-inner"}><span className={"kd-list-icon"} aria-hidden={"true"}><i aria-hidden={"true"} className={"keydesign-icon at-users"} /></span><span className={"kd-list-content"}><h6 className={"kd-list-title"}>Client portal</h6></span></div></a></li><li className={"kd-list-item elementor-repeater-item-f08b1a8"} role={"listitem"}><a href={"#section3"} className={"kd-list-link"}><div className={"kd-list-inner"}><span className={"kd-list-icon"} aria-hidden={"true"}><i aria-hidden={"true"} className={"keydesign-icon at-calendar-schedule"} /></span><span className={"kd-list-content"}><h6 className={"kd-list-title"}>Projects &amp; tasks</h6></span></div></a></li></ul></div></div></div></div></div>
  );
}
